name: Visit

on:
  issues:
    types: [opened]

jobs:
  UpdateCanvas:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'visitREADME')

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Test run (;
        run: |
          python update.py \ 
          --token ${{ secrets.GITHUB_TOKEN }} \
          --issue ${{ github.event.issue }}
